spring:
  profiles:
    active: @spring.active@
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.dra.mqtt.entity
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  configuration:
    log-impl:
      pagehelper: org.apache.ibatis.logging.stdout.StdOutImpl
